name: Execute automated checks
on:
    - push
jobs:
    # https://github.com/golangci/golangci-lint-action#how-to-use
    go-lint:
        name: Lint go code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout git repo
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  # renovate: datasource=github-releases depName=golang/go
                  go-version: "1.23"
            - name: Lint go code with golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
                  version: v1.56.2
    go-test:
        name: Verify go tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout git repo
              uses: actions/checkout@v4
            - name: Setup golang
              uses: actions/setup-go@v5
              with:
                  # renovate: datasource=github-releases depName=golang/go
                  go-version: "1.23"
            - name: Print go version
              run: go version
            - name: Execute go tests
              run: go test -v ./...
