name: Go Lint and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test: # This is the job ID
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  # renovate: datasource=github-releases depName=golang/go
                  go-version: "1.23"

            - name: Print Go version
              run: go version

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  # renovate: datasource=github-releases depName=golangci/golangci-lint
                  version: v1.56.2

            - name: Run tests
              run: go test -v ./...
