name: Go Lint and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
            - name: Set up Go
              uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
              with:
                  # renovate: datasource=github-tags depName=golang/go
                  go-version: '1.23.2'

            - name: Print Go version
              run: go version

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6
              with:
                  # renovate: datasource=github-releases depName=golangci/golangci-lint
                  version: v1.61.0
                  args: --verbose --concurrency=2

            - name: Run tests
              run: go test -v ./...
