name: Weekly Tag

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at 00:00 UTC
  workflow_dispatch:  # Allow manual triggers

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet @{1.week.ago} HEAD || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Get latest version
        id: get_latest_version
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0")
          latest_version=${latest_tag#v}
          new_version=$((latest_version + 1))
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ steps.get_latest_version.outputs.new_version }} -m "Weekly tag v${{ steps.get_latest_version.outputs.new_version }}"
          git push origin v${{ steps.get_latest_version.outputs.new_version }}
